version: "3.9"
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: "always"
    command: redis-server --requirepass G0rDkQtRcl!E --appendonly yes
    volumes:
      - "./redis/data:/data"

  api:
    build:
      context: .
    ports:
      - 5001:5000
    command: ["python", "entrypoint.py"]
    restart: "always"
    environment:
      # - CITY_PYO=https://api.hcu-dev.de/citypyo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=G0rDkQtRcl!E

  worker_1:
    build:
      context: .
    restart: "always"
    command: celery -A tasks worker --loglevel=info --concurrency=1 -n worker1@%h
    environment:
      # - CITY_PYO=YOUR_CITY_PYO_ENDPOINT
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=G0rDkQtRcl!E
    deploy:
      resources:
        limits:
          cpus: '2'

  worker_2:
    build:
      context: .
    restart: "always"
    command: celery -A tasks worker --loglevel=info --concurrency=1 -n worker2@%h
    environment:
      # - CITY_PYO=YOUR_CITY_PYO_ENDPOINT
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=G0rDkQtRcl!E
    deploy:
      resources:
        limits:
          cpus: '2'