FROM ubuntu

# Update the repository sources list
RUN apt-get update

# Install java
RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive \
    apt-get -y install \
      default-jre-headless \
  && \
  apt-get -y install \
      openjdk-8-jre-headless \
  && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN apt-get install -y java-common


# install python3
RUN : \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        software-properties-common \
    && add-apt-repository -y ppa:deadsnakes \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        python3.8-venv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && :

RUN python3.8 -m venv /venv
ENV PATH=/venv/bin:$PATH

# move files to dir
COPY . /app
WORKDIR /app

RUN pip install -r noise_analysis/requirements.txt

# run cityPyo listener
CMD ["python", "cityPyo_listener.py"]