version: "3.9"
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: "always"
    command: redis-server --requirepass YOUR_PASS --appendonly yes
    volumes:
      - "./redis/data:/data"

  api:
    build:
      context: .
    ports:
      - 5001:5001
    command: ["python", "entrypoint.py"]  # use entrypoint.sh for production  
    restart: "always"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=YOUR_PASS
      - CITY_PYO=https://YOUR_CITY_PYO_URL
      - CLIENT_ID=YOUR_ID
      - CLIENT_PASSWORD=YOUR_PASSWORD

  worker_1:
    build:
      context: .
    restart: "always"
    command: celery -A tasks worker --loglevel=info --concurrency=1 -n worker1@%h
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=YOUR_PASS
      - CITY_PYO=https://YOUR_CITY_PYO_URL
    deploy:
      resources:
        limits:
          cpus: '2'

  worker_2:
    build:
      context: .
    restart: "always"
    command: celery -A tasks worker --loglevel=info --concurrency=1 -n worker2@%h
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=YOUR_PASS
      - CITY_PYO=https://YOUR_CITY_PYO_URL
    deploy:
      resources:
        limits:
          cpus: '2'