FROM ubuntu

# Update the repository sources list
RUN apt-get update
# Install python-pip
#RUN apt-get install -y python
#RUN apt-get install -y python-pip
#RUN apt-get install -y libpq-dev python-dev

RUN apt-get install -y java-common
RUN apt install -y default-jre
RUN apt install -y openjdk-8-jre-headless

RUN : \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        software-properties-common \
    && add-apt-repository -y ppa:deadsnakes \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        python3.8-venv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && :

RUN python3.8 -m venv /venv
ENV PATH=/venv/bin:$PATH

# move files to dir
COPY . /app
WORKDIR /app

RUN pip install -r requirements.txt
RUN pip install -r noise_analysis/requirements.txt

# CMD ["bash", "entrypoint.sh"]
CMD ["python", "-u", "entrypoint.py"]