services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: "always"
    command: redis-server --requirepass ${REDIS_PASS:-devredis} --appendonly yes
    volumes:
      - "./redis/data:/data"

  api:
    build:
      context: .
    ports:
      - 5001:5001
    command: ["python", "entrypoint.py"]  # use entrypoint.sh for production  
    restart: "always"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=${REDIS_PASS:-devredis}
      - CITY_PYO=${CITY_PYO:-/app/fixtures/citypyo}
      - CLIENT_ID=${CLIENT_ID:-dev}
      - CLIENT_PASSWORD=${CLIENT_PASSWORD:-dev}
      - NOISE_ENGINE=${NOISE_ENGINE:-legacy}
      - CELERY_QUEUE=${CELERY_QUEUE:-noise}
      - NOISEMODELLING_RUNNER=/app/NoiseModelling/wps_scripts/build/install/NoiseModelling_without_gui/bin/wps_scripts

  worker_1:
    build:
      context: .
    cpus: '${WORKER_CPUS:-2}'
    restart: "always"
    command: celery -A tasks worker --loglevel=info --concurrency=1 -n worker1@%h
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=${REDIS_PASS:-devredis}
      - CITY_PYO=${CITY_PYO:-/app/fixtures/citypyo}
      - NOISE_ENGINE=${NOISE_ENGINE:-legacy}
      - CELERY_QUEUE=${CELERY_QUEUE:-noise}
      - NOISEMODELLING_RUNNER=/app/NoiseModelling/wps_scripts/build/install/NoiseModelling_without_gui/bin/wps_scripts
    deploy:
      resources:
        limits:
          cpus: '${WORKER_CPUS:-2}'

  worker_2:
    build:
      context: .
    cpus: '${WORKER_CPUS:-2}'
    restart: "always"
    command: celery -A tasks worker --loglevel=info --concurrency=1 -n worker2@%h
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=${REDIS_PASS:-devredis}
      - CITY_PYO=${CITY_PYO:-/app/fixtures/citypyo}
      - NOISE_ENGINE=${NOISE_ENGINE:-legacy}
      - CELERY_QUEUE=${CELERY_QUEUE:-noise}
      - NOISEMODELLING_RUNNER=/app/NoiseModelling/wps_scripts/build/install/NoiseModelling_without_gui/bin/wps_scripts
    deploy:
      resources:
        limits:
          cpus: '${WORKER_CPUS:-2}'
